variable "region" {}
variable "aws_vpc_id" {}
variable "subnet1" {}
variable "subnet2" {}
variable "key_name" {}
variable "iam_profile" {}
variable "iam_image" {}
variable "instance_type" {}
variable "asg_max" {}
variable "asg_min" {}
variable "asg_desired" {}